# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"UCF101": "01_dataset_ucf101.ipynb",
         "SingleFrameDataset": "01_dataset_ucf101.ipynb",
         "BatchShower": "01_dataset_ucf101.ipynb",
         "AVI": "02_avi.ipynb",
         "Rescale": "04_data_augmentation.ipynb",
         "RandomCrop": "04_data_augmentation.ipynb",
         "ToTensor": "04_data_augmentation.ipynb",
         "Normalize": "04_data_augmentation.ipynb",
         "RandomHorizontalFlip": "04_data_augmentation.ipynb",
         "AddRandomBrightness": "04_data_augmentation.ipynb",
         "ResNet50Classifier": "05_models.ipynb",
         "ResNet152Classifier": "05_models.ipynb"}

modules = ["dataset_ucf101.py",
           "avi.py",
           "data_augmentation.py",
           "models.py"]

doc_url = "https://andreamunafo.github.io/actions_in_videos/"

git_url = "https://github.com/andreamunafo/actions_in_videos/tree/master/"

def custom_doc_links(name): return None
